# Generated by Django 4.1.2 on 2023-08-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfoModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('tution_fee', models.IntegerField()),
                ('section', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherInfoModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('salary', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='roll',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
