# Generated by Django 4.1.2 on 2023-06-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_employeemodel_managermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('attendence', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('first_app.friend',),
        ),
    ]
