# Generated by Django 4.1.2 on 2023-08-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=40)),
                ('fathers_name', models.CharField(max_length=30)),
            ],
        ),
    ]
