# Generated by Django 4.1.2 on 2023-06-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credit',
            new_name='marks',
        ),
    ]
